#
# app.conf - Splunk Excel Extraction
#

[id]
name = splunk_excel_extract
version = 1.2.0

[install]
state = enabled
build = 3

[ui]
is_visible = true
label = Splunk Excel Extraction

[launcher]
author = Bichoumac
description = Download Splunk search results as a native Excel (.xlsx) file from a Simple XML dashboard button, using SheetJS in the browser.
version = 1.2.0

[package]
id = splunk_excel_extract
check_for_updates = true
